### PR TITLE
Allow AWS credentials to be passed in via config

### PR DESCRIPTION
**Pull request by keithpitt**
This PR is more of a "is this even a thing we wanna do" type change. No dramas if it's totally wrong, happy to drop it and do it another way.

I have this snippet of YAML:

```
aws_auth:
  aws_access_key_id: $AWS_ACCESS_KEY_ID
  aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
```

I need to login to ECR using those credentials. From my understanding, if `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are present, it'll use those values (and ignore any instance creds or things on the file system) https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

My goal is to allow something like this:

```
steps:
  - command: ./run_build.sh
    plugins:
      - ecr#v2.0.0:
          login: true
          access_key_id: 1234
          secret_access_key_env: $ECR_PASSWORD
```

Am I barking up the wrong tree? Is this sorta thing legit?

### CODE REVIEW

**Comment by keithpitt** [comment]
I did a test locally and it seems to be doing the right thing. I really don't like this bit:

```
export AWS_SECRET_ACCESS_KEY="${!BUILDKITE_PLUGIN_ECR_SECRET_ACCESS_KEY_ENV}"
```

Is there a better way I can do this?

**Comment by toolmantim** [comment]
Could you describe a little more about the context surrounding this? In general, setting up the AWS credentials is a little out of scope for this plugin… it assumes you've either set it up via another plugin, using an instance role on the agent, or some other mechanism.

**Comment by toolmantim** [comment]
Are you still needing this one @keithpitt? In general passing plain-vanilla creds through the pipeline.yml uploads are bad, because it exposes the creds to Buildkite. It might be best to close this PR and we can find another way to achieve what you're trying to do?

**Comment by keithduncan** [comment]
Let’s close this one! Sorry @keithpitt no pipeline env AWS creds for you 😛

**Pull request closed without merging**
