### PR TITLE
Remove support for aws-cli prior to v1.7.10 (2020-01-25)

### PR DESCRIPTION
**Pull request by pda**
`aws ecr get-login-password` was added in v1.7.10 (2020-01-25).
`aws ecr get-login` was subsequently removed in awscli 2.0.0.

We have supported both code paths, at the cost of a fair bit of complexity. This patch removes all the code and tests that supported versions older than v1.7.10.

This means systems using `aws-cli` older than v1.7.10 would need to upgrade that tool, or pin to an older version of this plugin.

I would also be okay with closing this PR, and maintaining the complexity to support older aws-cli, if anyone thinks that's still something people use.

### CODE REVIEW

**Comment by sj26** [comment]
Do we have any idea what the version usage might be like?

**Comment by pda** [comment]
Actually I have no idea about version usage.

I started considering this patch in the context of it being [submoduled into elastic-ci-stack-for-aws](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/master/.gitmodules#L5-L7), and thought it was _only_ used in elastic-stack, as is the case for `plugins/secrets`. Then I realised it was a widely used plugin, and figured I'd see what the diff looked like and float the idea anyway :)

All the elastic-ci-stack-for-aws usage will be safe, but people specifying it as an unpinned pipeline plugin could be running it against any aws-cli version.

**Comment by pda** [comment]
I wonder if a year later we feel more confident about dropping support for old aws-cli.

The `+3 / −363` delta is quite compelling.

aws-cli v1.7.10 was released 2020-01-25, so that's more than two years ago now.
But, without usage metrics, I'm not really confident that it _isn't_ still widely used.

**Comment by ryansdwilson** [comment]
@pzeballos and others... could this get merged in? The new support for the profile command doesn't work as if you're running a version of the tool newer than the pinned version 1.17.10 ie 2. the login_using_aws_ecr_get_login_password branch of code never gets called.

**Comment by toote** [comment]
@ryansdwilson as far as I understand there is no pinned version here, just a detection of the version present in the machine the step is running on so no releases on this plugin will fix that.

We're currently discussing doing this before the end of the year but there are no decisions made just yet. If anyone has a strong opinion on either side of the fence, we're all ears!

**Comment by toote** [comment]
I will close this issue as there may be reasons to decide either way so I believe that maintaining the status quo may be a better path for the time being. If `awscli` version 1 is ever sunset, I belive that should be the point in which it would be obvious to remove old support.

For reference these are the things we could come up with for and against the deprecation.

### Arguments *for* doing the change:

* reduces code complexity
* the compatibility is for a version that is 2.5 years old now
* some features or options are only compatible with newer versions (the last 2 releases at least)
* simplifies documentation, examples and clarifications

### Arguments *against* the change:

* aws cli version 1 is still being maintained and released
* some people may be running AMIs/OSs with LTS versions and can't or won't upgrade for 5+ years
* running other projects with old python versions and can't upgrade to newer awscli
* users may still inadvertently try to run the plugin and run into errors due to lack of checking versions

**Pull request closed without merging**
